fix CI

diff --git a/.github/workflows/lint.yml b/.github/workflows/lint.yml
--- a/.github/workflows/lint.yml
+++ b/.github/workflows/lint.yml
@@ -28,14 +28,8 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - name: Set up Python
-        uses: actions/setup-python@v4
-        with:
-          python-version: '3.x'
-      - name: Install vint
-        run: pip install vim-vint
       - name: Run vint
-        run: vint -Vsct --enable-neovim ./conf/.config/nvim/init.vim
+        uses: reviewdog/action-vint@v1
   lint-actionlint:
     runs-on: ubuntu-latest
     steps:
@@ -51,4 +45,4 @@ jobs:
           curl -L https://github.com/vmchale/tomlcheck/releases/download/0.1.0.38/tomlcheck-x86_64-unkown-linux-gnu -o /usr/local/bin/tomlcheck
           chmod 755 /usr/local/bin/tomlcheck
       - name: Run tomlcheck
-        run: find . -type f -name '*.toml' -printf '%p\n' | xargs -i -t -n 1 sh -c 'tomlcheck -f {} || echo "::error file={}::Toml lint check failed"'
+        run: find . -type f -name '*.toml' -printf '%P\n' | xargs -t -I{} -n1 sh -c 'tomlcheck -f {} || echo "::error file={}::Toml lint check failed"'
