fix(chezmoi): add check for .zshrc existence before running zsh command

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -31,7 +31,9 @@ jobs:
           sudo apt-get install -y --no-install-recommends zsh
         if: runner.os == 'Linux'
       - name: Test zsh
-        run: zsh -i -c "exit 0"
+        run: |
+          test -f ~/.zshrc || (echo "~/.zshrc not found" && exit 1)
+          zsh -i -c "exit 0"
   test-neovim:
     runs-on: ${{ matrix.os }}
     defaults:
